[package]
name = "overview-example"
version = "0.1.0"
authors = ["kepler0 <saveuselon@gmail.com>"]
edition = "2018"
workspace = "../.."

[[bin]]
name = "overview-example"
path = "src/main.rs"

[dependencies]
reclutch = { path = "../../" }
