[package]
name = "reclutch"
version = "0.1.0"
authors = ["jazzfool <saveuselon@gmail.com>"]
edition = "2018"

[dependencies]
euclid = "0.20.3"
failure = "0.1.6"
font-kit = "0.4.0"
palette = "0.4.1"

[workspace]
members = [
    ".",
    "examples/overview"
]
