[package]
name = "reclutch"
version = "0.0.0"
authors = ["jazzfool <saveuselon@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust UI Core"
homepage = "http://github.com/jazzfool/reclutch"
repository = "http://github.com/jazzfool/reclutch"

[features]
default = ["reclutch_derive"]
skia = ["skia-safe", "gl", "indexmap"]

[dependencies]
reclutch_event = { path = "../event" }
reclutch_derive = { path = "../derive", optional = true }
euclid = "0.20.3"
thiserror = "1.0.5"
font-kit = "0.4.0"
palette = "0.4.1"
skia-safe = { version = "0.18.0", optional = true }
gl = { version = "0.14.0", optional = true }
indexmap = { version = "1.3.0", optional = true }

[dev-dependencies]
glutin = "0.22.0-alpha3"
