[package]
name = "reclutch"
version = "0.0.0"
authors = ["jazzfool <saveuselon@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust UI Core"
homepage = "http://github.com/jazzfool/reclutch"
repository = "http://github.com/jazzfool/reclutch"

[features]
default = ["reclutch_derive"]
skia = ["skia-safe", "gl", "linked-hash-map"]

[dependencies]
reclutch_event = { path = "../event" }
reclutch_derive = { path = "../derive", optional = true }
euclid = "0.20.3"
thiserror = "1.0.5"
font-kit = "0.4.0"
palette = "0.4.1"
skia-safe = { version = "0.19.0", optional = true }
gl = { version = "0.14.0", optional = true }
linked-hash-map = { version = "0.5.2", optional = true }

[[example]]
name = "counter"
required-features = ["skia"]

[[example]]
name = "image_viewer"
required-features = ["skia"]

[[example]]
name = "opengl"
required-features = ["skia"]

[dev-dependencies.glium]
version = "0.26.0-alpha3"

[dev-dependencies.nalgebra]
version = "0.19.0"

[[example]]
name = "shaping"
required-features = ["skia"]

[dev-dependencies.harfbuzz_rs]
version = "1.0.0"

[dev-dependencies.rusttype]
version = "0.8.1"

[dev-dependencies]
glutin = "0.22.0-alpha3"
float-cmp = "0.5.3"
