[package]
name = "reclutch"
version = "0.0.0"
authors = ["jazzfool <saveuselon@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Rust UI Core"
homepage = "http://github.com/jazzfool/reclutch"
repository = "http://github.com/jazzfool/reclutch"

[dependencies]
reclutch_event = { path = "../reclutch_event" }
euclid = "0.20.3"
failure = "0.1.6"
font-kit = "0.4.0"
palette = "0.4.1"

[dev-dependencies]
raqote = "0.7.4"
pixels = { git = "https://github.com/parasyte/pixels" }
winit = "0.20.0-alpha4"
